# Generated by Django 4.1.3 on 2024-01-07 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhpnwapi', '0002_alter_order_subtotal_alter_order_tax_alter_order_tip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhpnwapi.menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhpnwapi.order')),
            ],
        ),
    ]
